version: 2
defaults:
  steps: &test-steps
    - composer self-update --stable
    - composer install
    - composer test
jobs:
  test-7.2:
    docker:
      image: circleci/php:7.2
    steps: *test-steps
  test-7.3:
    docker:
      image: circleci/php:7.3
    steps: *test-steps
  test-7.4:
    docker:
      image: circleci/php:7.4
    steps: *test-steps
