version: 2.1
defaults:
  steps: &test-steps
    - checkout
    - run: |
        if [[ -n "$CIRCLE_PULL_REQUEST" ]]; then
            curl $(php -r 'echo preg_replace("|^(https?://)(www\.)?github.com/(.+/pull).*(/\d+)|i", "$1api.github.com/repos/$3s$4", getenv("CIRCLE_PULL_REQUEST"));') \
              -o pr-info.json
            git fetch && git merge origin/$(php -r 'echo json_decode(file_get_contents("pr-info.json"), true)["base"]["ref"];') --no-edit
        fi
    - run: composer self-update --stable
    - run: composer install
    - run: composer test
jobs:
  test-72:
    docker:
      - image: circleci/php:7.2
    steps: *test-steps
  test-73:
    docker:
      - image: circleci/php:7.3
    steps: *test-steps
  test-74:
    docker:
      - image: circleci/php:7.4
    steps: *test-steps
workflows:
  version: 2
  test-all-platforms:
    jobs:
      - test-72
      - test-73
      - test-74
