version: 2.1
defaults:
  steps: &test-steps
    - checkout
    - run: composer self-update --stable
    - run: composer install
    - run: composer test
jobs:
  test-7.2:
    docker:
      image: circleci/php:7.2
    steps: *test-steps
  test-7.3:
    docker:
      image: circleci/php:7.3
    steps: *test-steps
  test-7.4:
    docker:
      image: circleci/php:7.4
    steps: *test-steps
workflows:
  version: 2
  test-all-platforms:
    jobs:
      - test-7.2
      - test-7.3
      - test-7.4
