version: 2.1
defaults:
  steps: &test-steps
    - checkout
    - run: composer self-update --stable
    - run: composer install
    - run: composer test
jobs:
  test-72:
    docker:
      image: circleci/php:7.2
    steps: *test-steps
  test-73:
    docker:
      image: circleci/php:7.3
    steps: *test-steps
  test-74:
    docker:
      image: circleci/php:7.4
    steps: *test-steps
workflows:
  version: 2
  test-all-platforms:
    jobs:
      - test-72
      - test-73
      - test-74
